obj-$(CONFIG_HELLO_TEST)     +=hello.o
obj-$(CONFIG_PARAM_TEST)     +=param.o
obj-$(CONFIG_GLOBALMEM_TEST) +=globalmem.o
obj-$(CONFIG_GLOBALFIFO_TEST) +=globalfifo.o
obj-$(CONFIG_SECOND_DEVICE_TEST) += seconddevice.o
obj-$(CONFIG_PLATFORM_DEVICE_DEMO) +=platform_device_demo.o
obj-$(CONFIG_PLATFORM_DRIVER_DEMO) +=platform_driver_demo.o
obj-$(CONFIG_MMAP_DRIVER)          +=mmap_kernel_driver.o

